plot_ly(g_300_S1, x = ~PartCount, y = ~abs(Torque), type = 'scatter',  mode = 'markers')


plot_ly(g_STorque, x = ~PartCount, y = ~abs(Mean), type = 'scatter',  mode = 'lines+markers', name="Mean") %>%
  layout(title = "<b>S1 Torque for Sister Tool</b>", yaxis = list(title = "abs(Torque)", range = c(0,5))) %>%
#        error_y = ~list(array = mad, color = '#000000')) %>%
  add_trace(y = ~abs(Median), type = 'scatter',  mode = 'lines+markers', name = "Median") %>%
  add_trace(y = ~mad, type = 'scatter',  mode = 'lines+markers', name = "mad", line = list(color = "red"), marker = list(color = "red"))


test<-data.frame(cbind(g_300_S1$PartCount, g_300_S1$Torque))
colnames(test)<-c("PartCount", "Torque")
test$PartCount<-as.factor(test$PartCount)
head(test)
glimpse(test)

test2<-test %>% pivot_wider(names_from = PartCount, values_from = Torque)
head(test2)
colnames(test2)
ncol(test2)

test2<-
  test%>%
  group_by(PartCount) %>%
  mutate(row = row_number()) %>%
  tidyr::pivot_wider(names_from = PartCount, values_from = Torque) %>%
  select(-row)

glimpse(test2)
test2<-na.omit(test2)



Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`0`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 1</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`1`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 2</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`2`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 3</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`3`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 4</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`4`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 5</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`5`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 6</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`6`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 7</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`7`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 8</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`8`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 9</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`9`), type = 'scatter',  mode = 'lines+markers') %>% layout(title = "<b>Part 10</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`10`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 11</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`11`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 12</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`12`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 13</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`13`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 14</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`14`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 15</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`15`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 16</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`16`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 17</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`17`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 18</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`18`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 19</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`19`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 20</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`20`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 21</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`21`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 22</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`22`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 23</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`23`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 24</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`24`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 25</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`25`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 26</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`26`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 27</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`27`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 28</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`28`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 29</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`29`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 30</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`30`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 31</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`31`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 32</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`32`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 33</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`33`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 34</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`34`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 35</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`35`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 36</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`36`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 37</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`37`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 38</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`38`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 39</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`39`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 40</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`40`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 41</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`41`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 42</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`42`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 43</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`43`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 44</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`44`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 45</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`45`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 46</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`46`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 47</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`47`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 48</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`48`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 49</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`49`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 50</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`50`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 51</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`51`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 52</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`52`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 53</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`53`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 54</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`54`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 55</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`55`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 56</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`56`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 57</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`57`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 58</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`58`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 59</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`59`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 60</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`60`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 61</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`61`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 62</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`62`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 63</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`63`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 64</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`64`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 65</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`65`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 66</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`66`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 67</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`67`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 68</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`68`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 69</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`69`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 70</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`70`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 71</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`71`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 72</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`72`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 73</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))
Sys.sleep(2)
plot_ly(test2, y = ~abs(test2$`73`), type = 'scatter', mode = 'lines+markers') %>% layout(title = "<b>Part 74</b>", yaxis = list(title = "abs(Torque)", range = c(0,5)))

